site_name: れいとの軌跡
theme:
  name: material

extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list

nav:
  - ホーム: index.md

  - ブログ:
      - 2025:
          - 12月:
            - "04": blog/2025/12/04.md
            - "05": blog/2025/12/05.md
            - "06": blog/2025/12/06.md
            - "07": blog/2025/12/07.md
            - "08": blog/2025/12/08.md
            - "09": blog/2025/12/09.md
            - "10": blog/2025/12/10.md

  - 作品:
      - 作品って？: works/index.md

  - 知見:
      - 未分類:
        - Github Ppages + MkDocsでサイト構築: knowledge/other/create_site_with_github_pages_and_mkdocs.md
      - Tips:
        - MkDocs: knowledge/tips/mkdocs.md